// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZqbwkryCJ12S-Q64rNHwG2G6IlKPToPE',
    appId: '1:633693508586:web:c208edec3bad5000499893',
    messagingSenderId: '633693508586',
    projectId: 'mini-e-commerce-39d10',
    authDomain: 'mini-e-commerce-39d10.firebaseapp.com',
    storageBucket: 'mini-e-commerce-39d10.firebasestorage.app',
    measurementId: 'G-005SYP77EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDluKrsPfBOh7Bw34Ev8G2pg6uRlpf3jgw',
    appId: '1:633693508586:android:2bd50cc69da3e981499893',
    messagingSenderId: '633693508586',
    projectId: 'mini-e-commerce-39d10',
    storageBucket: 'mini-e-commerce-39d10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1_hdTReAvheZWdXEieifcMq5biYJSWRw',
    appId: '1:633693508586:ios:842e1e915362c88a499893',
    messagingSenderId: '633693508586',
    projectId: 'mini-e-commerce-39d10',
    storageBucket: 'mini-e-commerce-39d10.firebasestorage.app',
    iosBundleId: 'com.example.miniCommerce',
  );
}
